export const IMAGES=[
    {
        src:'/images/background1.jpg',
        alt:'background-1'
    },
    {
        src:'/images/background2.jpg',
        alt:'background-2'
    },
    {
        src:'/images/background3.jpg',
        alt:'background-3'
    },
    {
        src:'/images/background4.jpg',
        alt:'background-4'
    },
    {
        src:'/images/background5.jpg',
        alt:'background-5'
    },
]